language: node_js
node_js:
  - "0.10"
before_install:
  - echo 'yes' | sudo add-apt-repository ppa:rethinkdb/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y rethinkdb
before_script:
  - cp config.js.example config.js
  - rethinkdb &
